FROM golang:1.16-alpine as builder
RUN mkdir -p /root/.ssh/ && \
    apk update && \
    apk add openssh && \
    apk add --no-cache build-base && \
    apk add --no-cache alpine-sdk && \
    rm -rf /var/cache/apk/*
ARG CGO_ENABLED=0

RUN go get github.com/helmutkemper/util@v0.0.0-20210420213725-d4fad0e09c93
RUN go get github.com/hashicorp/memberlist@v0.3.0
RUN go get github.com/google/btree@v0.0.0-20180813153112-4030bb1f1f0c
RUN go get github.com/armon/go-metrics@v0.0.0-20180917152333-f0300d1749da
RUN go get github.com/hashicorp/go-multierror@v1.0.0
RUN go get github.com/hashicorp/go-sockaddr@v1.0.0
RUN go get github.com/miekg/dns@v1.1.26
RUN go get github.com/sean-/seed@v0.0.0-20170313163322-e2103e2c3529
RUN go get github.com/stretchr/testify@v1.7.0
RUN go get github.com/pmezard/go-difflib@v1.0.0
RUN go get gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c
RUN go get github.com/davecgh/go-spew@v1.1.1
RUN go get golang.org/x/crypto@v0.0.0-20200622213623-75b288015ac9
RUN go get golang.org/x/net@v0.0.0-20200822124328-c89045814202
RUN go get golang.org/x/sys@v0.0.0-20200323222414-85ca7c5b95cd
RUN go get golang.org/x/sync@v0.0.0-20190423024810-112230192c58
RUN go get github.com/hashicorp/errwrap@v1.0.0
RUN go get github.com/hashicorp/go-immutable-radix@v1.0.0
RUN go get github.com/pascaldekloe/goe@v0.0.0-20180627143212-57f6aae5913c
RUN go get github.com/hashicorp/golang-lru@v0.5.0
RUN go get github.com/hashicorp/go-uuid@v1.0.0
