FROM golang:1.16-alpine as builder
RUN mkdir -p /root/.ssh/ && \
    apk update && \
    apk add openssh && \
    apk add --no-cache build-base && \
    apk add --no-cache alpine-sdk && \
    rm -rf /var/cache/apk/*
ARG CGO_ENABLED=0

RUN go get github.com/nats-io/nats.go@v1.11.1-0.20210623165838-4b75fc59ae30
RUN go get github.com/helmutkemper/util
RUN go get google.golang.org/grpc@v1.36.0
RUN go get github.com/beevik/ntp@v0.3.0
RUN go get golang.org/x/net@v0.0.0-20210226172049-e18ecbb05110
RUN go get golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9
RUN go get github.com/golang/protobuf@v1.4.2
RUN go get github.com/google/go-cmp@v0.5.6
RUN go get gopkg.in/yaml.v2@v2.3.0
RUN go get golang.org/x/text@v0.3.3
RUN go get github.com/brianvoe/gofakeit/v6@v6.7.0
RUN go get github.com/nats-io/nats-server/v2@v2.3.4
RUN go get golang.org/x/crypto@v0.0.0-20210616213533-5ff15b29337e
RUN go get github.com/klauspost/compress@v1.11.12
RUN go get github.com/minio/highwayhash@v1.0.1
RUN go get github.com/nats-io/jwt@v1.2.2
RUN go get golang.org/x/sys@v0.0.0-20210615035016-665e8c7367d1
RUN go get github.com/nats-io/jwt/v2@v2.0.3
RUN go get golang.org/x/time@v0.0.0-20200416051211-89c76fbcd5d1
RUN go get github.com/nats-io/nats.go
RUN go get github.com/go-redis/redis/v8
RUN go get github.com/hashicorp/memberlist@v0.2.4
RUN go get google.golang.org/grpc@v1.39.0
RUN go get github.com/armon/go-metrics@v0.0.0-20180917152333-f0300d1749da
RUN go get github.com/google/btree@v0.0.0-20180813153112-4030bb1f1f0c
RUN go get github.com/hashicorp/go-msgpack@v0.5.3
RUN go get github.com/hashicorp/go-multierror@v1.0.0
RUN go get github.com/hashicorp/go-sockaddr@v1.0.0
RUN go get github.com/miekg/dns@v1.1.26
RUN go get github.com/sean-/seed@v0.0.0-20170313163322-e2103e2c3529
RUN go get github.com/stretchr/testify@v1.5.1
RUN go get github.com/golang/protobuf@v1.5.0
RUN go get github.com/google/go-cmp@v0.5.5
RUN go get golang.org/x/net@v0.0.0-20200822124328-c89045814202
RUN go get github.com/hashicorp/go-immutable-radix@v1.0.0
RUN go get github.com/pascaldekloe/goe@v0.0.0-20180627143212-57f6aae5913c
RUN go get github.com/hashicorp/errwrap@v1.0.0
RUN go get golang.org/x/crypto@v0.0.0-20200622213623-75b288015ac9
RUN go get golang.org/x/sys@v0.0.0-20200323222414-85ca7c5b95cd
RUN go get golang.org/x/sync@v0.0.0-20190423024810-112230192c58
RUN go get github.com/hashicorp/golang-lru@v0.5.0
RUN go get github.com/hashicorp/go-uuid@v1.0.0
RUN go get github.com/davecgh/go-spew@v1.1.1
RUN go get github.com/pmezard/go-difflib@v1.0.0
RUN go get gopkg.in/yaml.v2@v2.2.3
RUN go get golang.org/x/text@v0.3.2
RUN go get golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1
